//! Generic show player: load a show file or a show folder, list what it
//! can do, drive it interactively or from a driver file.
//!
//! ```sh
//! cargo run --example player -- path/to/show[.json] [path/to/driver.json]
//! ```
//!
//! A show folder is the self-contained form of a show:
//!
//! ```text
//! myshow/
//!   show.json           the show document (required)
//!   test-driver.json    optional driver, picked up automatically
//!   assets/             PNGs (any color type or bit depth) registered as
//!                       images by filename stem
//!     fonts/            bitmap fonts (.fnt plus page PNGs), registered by
//!                       .fnt filename stem
//! ```
//!
//! A bare `.json` path plays a single show file instead. With no arguments
//! the bundled minigolf show plays. The player inspects the model and
//! prints its actions (trigger names) and variables to the console: type
//! an action's number or name to fire it, `name=value` to set a variable,
//! `q` to quit. Digit keys in the window fire actions too, escape quits.
//!
//! A driver file scripts the same commands with delays, standing in for a
//! live host; next to a loose show file the convention is
//! `<show>.test-driver.json` (see `examples/shows/`):
//!
//! ```json
//! {
//!   "loop": true,
//!   "steps": [
//!     { "set": { "score": 0 } },
//!     { "wait": 0.5 },
//!     { "trigger": "go" }
//!   ]
//! }
//! ```
//!
//! Console and keyboard input keep working while a driver runs.
//!
//! Images a show references but nobody registered are logged as warnings
//! at load and skipped (the slideshow's are generated by its own host
//! code, so they stay missing here).

use std::collections::BTreeSet;
use std::io::BufRead;
use std::sync::mpsc::{Receiver, Sender};
use std::sync::Arc;
use std::time::{Duration, Instant};

use cuelight::render::{background_color, build_vello_scene, ImageCache, OutputPass};
use cuelight::vello;
use cuelight::{BitmapFont, Engine, Layer, LayerKind, OutputMode, Show, Value};
use vello::kurbo::Affine;
use vello::peniko::{Color, ImageBrush};
use vello::util::{RenderContext, RenderSurface};
use vello::wgpu;
use wgpu::CurrentSurfaceTexture;
use winit::application::ApplicationHandler;
use winit::dpi::LogicalSize;
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, ControlFlow, EventLoop};
use winit::keyboard::{Key, NamedKey};
use winit::window::{Window, WindowId};

mod common;

/// A scripted command sequence with delays, standing in for a live host.
#[derive(Debug, Clone, serde::Deserialize)]
struct Driver {
    #[serde(default, rename = "loop")]
    looping: bool,
    #[serde(default)]
    steps: Vec<Step>,
}

/// One driver step: exactly one of `wait` (seconds), `trigger` (fire an
/// action) or `set` (variable assignments).
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(untagged)]
enum Step {
    Wait {
        wait: f64,
    },
    Trigger {
        trigger: String,
    },
    Set {
        set: std::collections::BTreeMap<String, Value>,
    },
}

/// Playback state for a loaded [`Driver`].
struct DriverState {
    driver: Driver,
    index: usize,
    wait_left: f64,
    done: bool,
}

impl DriverState {
    fn new(driver: Driver) -> Self {
        Self {
            driver,
            index: 0,
            wait_left: 0.0,
            done: false,
        }
    }
}

fn fmt_value(value: &Value) -> String {
    match value {
        Value::Text(text) => format!("{text:?}"),
        other => other.to_text(),
    }
}

/// Collect every trigger name the show declares: scene triggers and
/// timeline triggers in any layer tree.
fn collect_show_actions(show: &Show, out: &mut BTreeSet<String>) {
    out.extend(show.scenes.iter().filter_map(|s| s.trigger.clone()));
    for layers in show.layer_trees() {
        collect_actions(layers, out);
    }
}

/// Collect every trigger name declared by timelines in the layer tree.
fn collect_actions(layers: &[Layer], out: &mut BTreeSet<String>) {
    for layer in layers {
        for timeline in &layer.timelines {
            if let Some(trigger) = &timeline.trigger {
                out.insert(trigger.clone());
            }
        }
        collect_actions(layer.children(), out);
    }
}

/// Warn (once, at load) about image and text layers whose pixels or font
/// nobody registered.
fn warn_missing_images(engine: &Engine, layers: &[Layer]) {
    let fonts = &engine.show().expect("show loaded").fonts;
    for layer in layers {
        match &layer.kind {
            LayerKind::Image { image, .. } if engine.image(image).is_none() => {
                log::warn!(
                    "image {image:?} (layer {:?}) is not registered; it will not render",
                    layer.name
                );
            }
            LayerKind::Text { font, .. } => {
                if let Some(style) = fonts.get(font).filter(|s| !engine.has_font(&s.file)) {
                    log::warn!(
                        "font {:?} (layer {:?}) is not registered; it will not render",
                        style.file,
                        layer.name
                    );
                }
            }
            _ => {}
        }
        warn_missing_images(engine, layer.children());
    }
}

fn print_menu(engine: &Engine, actions: &[String]) {
    let show = engine.show().expect("show loaded");
    println!(
        "\nplaying {:?} ({}x{})",
        show.name, show.size[0], show.size[1]
    );
    if actions.is_empty() {
        println!("actions: none declared");
    } else {
        println!("actions:");
        for (i, action) in actions.iter().enumerate() {
            println!("  {}) {action}", i + 1);
        }
    }
    if !show.scenes.is_empty() {
        let scenes: Vec<&str> = show.scenes.iter().map(|s| s.name.as_str()).collect();
        println!(
            "scenes: {} (active: {})",
            scenes.join(", "),
            engine.active_scene().unwrap_or("none")
        );
    }
    if !show.variables.is_empty() {
        println!("variables:");
        for (name, value) in &show.variables {
            println!("  {name} = {}", fmt_value(value));
        }
    }
    println!("type an action number or name, name=value to set a variable, q to quit");
}

/// Read console lines on a background thread; the event loop polls them.
fn spawn_console_reader(tx: Sender<String>) {
    std::thread::spawn(move || {
        for line in std::io::stdin().lock().lines() {
            let Ok(line) = line else { break };
            let line = line.trim().to_owned();
            if !line.is_empty() && tx.send(line).is_err() {
                break;
            }
        }
    });
}

struct RenderState {
    window: Arc<Window>,
    surface: RenderSurface<'static>,
}

/// The show rendered at its own resolution, for output modes that convert
/// the finished frame (gray levels, tint) before it is scaled into the
/// window. The converted texture is registered with vello as an image.
struct NativeFrame {
    render: wgpu::TextureView,
    converted: wgpu::TextureView,
    image: vello::peniko::ImageData,
    pass: OutputPass,
}

impl NativeFrame {
    fn new(
        device: &wgpu::Device,
        renderer: &mut vello::Renderer,
        [width, height]: [u32; 2],
    ) -> Self {
        let texture = |label, usage| {
            device.create_texture(&wgpu::TextureDescriptor {
                label: Some(label),
                size: wgpu::Extent3d {
                    width,
                    height,
                    depth_or_array_layers: 1,
                },
                mip_level_count: 1,
                sample_count: 1,
                dimension: wgpu::TextureDimension::D2,
                format: wgpu::TextureFormat::Rgba8Unorm,
                usage,
                view_formats: &[],
            })
        };
        let render = texture(
            "cuelight-native",
            wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::TEXTURE_BINDING,
        );
        let converted = texture(
            "cuelight-native-output",
            wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::COPY_SRC,
        );
        let converted_view = converted.create_view(&wgpu::TextureViewDescriptor::default());
        Self {
            render: render.create_view(&wgpu::TextureViewDescriptor::default()),
            converted: converted_view,
            image: renderer.register_texture(converted),
            pass: OutputPass::new(device),
        }
    }
}

struct App {
    engine: Engine,
    actions: Vec<String>,
    driver: Option<DriverState>,
    console: Receiver<String>,
    context: RenderContext,
    // One vello renderer per wgpu device the context hands out.
    renderers: Vec<Option<vello::Renderer>>,
    state: Option<RenderState>,
    occluded: bool,
    last_frame: Instant,
    fps: common::Fps,
    images: ImageCache,
    native: Option<NativeFrame>,
}

impl App {
    fn fire_action(&mut self, index: usize) {
        match self.actions.get(index) {
            Some(action) => {
                log::info!("firing action {:?}", action);
                let action = action.clone();
                self.engine.trigger(&action);
            }
            None => log::warn!("no action number {}", index + 1),
        }
    }

    /// Apply one console command; returns false when the player should quit.
    fn handle_command(&mut self, command: &str) -> bool {
        match command {
            "q" | "quit" | "exit" => {
                log::info!("quit requested on console");
                return false;
            }
            _ => {}
        }
        if let Some((name, value)) = command.split_once('=') {
            let (name, value) = (name.trim(), value.trim());
            match value.parse::<f64>() {
                Ok(number) => {
                    log::info!("setting variable {name:?} = {number}");
                    self.engine.set_variable(name, number);
                }
                Err(_) => log::warn!("{value:?} is not a number"),
            }
        } else if let Ok(number) = command.parse::<usize>() {
            self.fire_action(number.wrapping_sub(1));
        } else {
            log::info!("firing action {command:?}");
            self.engine.trigger(command);
        }
        true
    }

    /// Advance the driver playhead by `dt`: waits consume time, commands
    /// execute the moment their wait is over.
    fn advance_driver(&mut self, mut dt: f64) {
        let Some(d) = &mut self.driver else { return };
        if d.done {
            return;
        }
        let mut wraps = 0;
        loop {
            if d.wait_left > 0.0 {
                if dt < d.wait_left {
                    d.wait_left -= dt;
                    return;
                }
                dt -= d.wait_left;
                d.wait_left = 0.0;
            }
            if d.index >= d.driver.steps.len() {
                if !d.driver.looping || d.driver.steps.is_empty() {
                    log::info!("driver finished");
                    d.done = true;
                    return;
                }
                wraps += 1;
                if wraps > 1 {
                    log::warn!("looping driver has no wait steps; stopping it");
                    d.done = true;
                    return;
                }
                log::debug!("driver loops, restarting");
                d.index = 0;
            }
            let step = d.driver.steps[d.index].clone();
            d.index += 1;
            match step {
                Step::Wait { wait } => d.wait_left = wait.max(0.0),
                Step::Trigger { trigger } => {
                    log::info!("driver fires action {trigger:?}");
                    self.engine.trigger(&trigger);
                }
                Step::Set { set } => {
                    for (name, value) in set {
                        log::info!("driver sets {name:?} = {}", fmt_value(&value));
                        self.engine.set_variable(&name, value);
                    }
                }
            }
        }
    }

    fn redraw(&mut self) {
        let now = Instant::now();
        let dt = now.duration_since(self.last_frame).as_secs_f64().min(0.1);
        self.last_frame = now;
        self.advance_driver(dt);
        let Some(state) = &self.state else { return };
        self.engine.advance_frame(dt);
        for event in self.engine.drain_events() {
            log::info!("show event: {event:?}");
        }

        // Fit the show into the window: uniform scale, centered.
        let [show_w, show_h] = self.engine.show().expect("show loaded").size;
        let surface = &state.surface;
        let (sw, sh) = (surface.config.width, surface.config.height);
        let scale = (f64::from(sw) / f64::from(show_w)).min(f64::from(sh) / f64::from(show_h));
        let tx = (f64::from(sw) - f64::from(show_w) * scale) / 2.0;
        let ty = (f64::from(sh) - f64::from(show_h) * scale) / 2.0;
        let placement = Affine::translate((tx, ty)) * Affine::scale(scale);
        let show_scene =
            build_vello_scene(&self.engine, &mut self.images).expect("build vello scene");
        let output = self.engine.output();
        let device_handle = &self.context.devices[surface.dev_id];
        let renderer = self.renderers[surface.dev_id]
            .as_mut()
            .expect("renderer for surface device");

        let mut frame = vello::Scene::new();
        if output.mode == OutputMode::Rgb {
            frame.append(&show_scene, Some(placement));
        } else {
            // Render at show resolution, convert on the GPU, then draw the
            // converted texture scaled into the window.
            let native = self.native.get_or_insert_with(|| {
                NativeFrame::new(&device_handle.device, renderer, [show_w, show_h])
            });
            renderer
                .render_to_texture(
                    &device_handle.device,
                    &device_handle.queue,
                    &show_scene,
                    &native.render,
                    &vello::RenderParams {
                        base_color: background_color(&self.engine),
                        width: show_w,
                        height: show_h,
                        antialiasing_method: vello::AaConfig::Area,
                    },
                )
                .expect("vello render");
            let mut encoder =
                device_handle
                    .device
                    .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                        label: Some("cuelight-output"),
                    });
            native.pass.encode(
                &device_handle.device,
                &mut encoder,
                &native.render,
                &native.converted,
                show_w,
                show_h,
                output,
            );
            device_handle.queue.submit([encoder.finish()]);
            renderer.mark_override_image_dirty(&native.image);
            frame.draw_image(&ImageBrush::new(native.image.clone()), placement);
        }
        self.fps.tick();
        self.fps.draw(&mut frame, state.window.scale_factor());

        // The letterbox around the show takes the converted background.
        let [r, g, b, a] = background_color(&self.engine).to_rgba8().to_u8_array();
        let [r, g, b, a] = output.apply_pixel([r, g, b, a]);
        renderer
            .render_to_texture(
                &device_handle.device,
                &device_handle.queue,
                &frame,
                &surface.target_view,
                &vello::RenderParams {
                    base_color: Color::from_rgba8(r, g, b, a),
                    width: sw,
                    height: sh,
                    antialiasing_method: vello::AaConfig::Area,
                },
            )
            .expect("vello render");

        // Blit the intermediate target to the window surface and present.
        let surface_texture = match surface.surface.get_current_texture() {
            CurrentSurfaceTexture::Success(t) | CurrentSurfaceTexture::Suboptimal(t) => t,
            CurrentSurfaceTexture::Outdated | CurrentSurfaceTexture::Lost => {
                // Reconfigure and skip this frame; the next redraw retries.
                self.context.configure_surface(surface);
                state.window.request_redraw();
                return;
            }
            CurrentSurfaceTexture::Timeout
            | CurrentSurfaceTexture::Occluded
            | CurrentSurfaceTexture::Validation => {
                // Retry throttled: without vsync pacing this path would
                // otherwise spin at full speed.
                std::thread::sleep(Duration::from_millis(100));
                state.window.request_redraw();
                return;
            }
        };
        let mut encoder =
            device_handle
                .device
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("cuelight-surface-blit"),
                });
        surface.blitter.copy(
            &device_handle.device,
            &mut encoder,
            &surface.target_view,
            &surface_texture
                .texture
                .create_view(&wgpu::TextureViewDescriptor::default()),
        );
        device_handle.queue.submit([encoder.finish()]);
        surface_texture.present();

        state.window.request_redraw();
    }
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.state.is_some() {
            return;
        }
        let [w, h] = self.engine.show().expect("show loaded").size;
        let window = Arc::new(
            event_loop
                .create_window(
                    Window::default_attributes()
                        .with_title("cuelight: player")
                        .with_inner_size(LogicalSize::new(w * 2, h * 2)),
                )
                .expect("create window"),
        );
        common::log_window_info(&window);
        let size = window.inner_size();
        let surface = pollster::block_on(self.context.create_surface(
            window.clone(),
            size.width.max(1),
            size.height.max(1),
            wgpu::PresentMode::AutoVsync,
        ))
        .expect("create surface");
        common::log_adapter(&self.context, surface.dev_id);
        self.renderers
            .resize_with(self.context.devices.len(), || None);
        self.renderers[surface.dev_id].get_or_insert_with(|| {
            vello::Renderer::new(
                &self.context.devices[surface.dev_id].device,
                vello::RendererOptions::default(),
            )
            .expect("create vello renderer")
        });
        self.state = Some(RenderState { window, surface });
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        match event {
            WindowEvent::CloseRequested => {
                log::info!("close requested, exiting");
                event_loop.exit();
            }
            WindowEvent::KeyboardInput { event, .. } if event.state.is_pressed() => {
                match &event.logical_key {
                    Key::Named(NamedKey::Escape) => {
                        log::info!("escape pressed, exiting");
                        event_loop.exit();
                    }
                    Key::Character(c) => {
                        if let Ok(digit) = c.as_str().parse::<usize>() {
                            self.fire_action(digit.wrapping_sub(1));
                        }
                    }
                    _ => {}
                }
            }
            WindowEvent::Resized(size) => {
                log::debug!("resized to {}x{} physical", size.width, size.height);
                if let Some(state) = &mut self.state {
                    if size.width > 0 && size.height > 0 {
                        self.context
                            .resize_surface(&mut state.surface, size.width, size.height);
                    }
                }
            }
            WindowEvent::Occluded(occluded) => {
                log::info!("window occluded: {occluded}");
                self.occluded = occluded;
                if !occluded {
                    if let Some(state) = &self.state {
                        state.window.request_redraw();
                    }
                }
            }
            // While occluded the redraw chain stops entirely; the
            // Occluded(false) event restarts it.
            WindowEvent::RedrawRequested if !self.occluded => self.redraw(),
            _ => {}
        }
    }

    fn about_to_wait(&mut self, event_loop: &ActiveEventLoop) {
        if common::ctrl_c_pressed() {
            event_loop.exit();
            return;
        }
        while let Ok(command) = self.console.try_recv() {
            if !self.handle_command(&command) {
                event_loop.exit();
                return;
            }
        }
        event_loop.set_control_flow(if self.occluded {
            // No redraws while hidden: wake periodically so ctrl-c and
            // console commands still land promptly.
            ControlFlow::WaitUntil(Instant::now() + Duration::from_millis(200))
        } else {
            ControlFlow::Wait
        });
    }
}

fn main() -> std::process::ExitCode {
    common::init_logging();
    common::install_ctrl_c_handler();
    match run() {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(e) => {
            log::error!("{e}");
            std::process::ExitCode::FAILURE
        }
    }
}

/// Decode a PNG into tightly packed RGBA8: any bit depth, palette and
/// grayscale images are converted (missing alpha becomes opaque).
fn load_png(path: &std::path::Path) -> Result<(u32, u32, Vec<u8>), String> {
    let file = std::fs::File::open(path).map_err(|e| e.to_string())?;
    let mut decoder = png::Decoder::new(std::io::BufReader::new(file));
    decoder.set_transformations(png::Transformations::normalize_to_color8());
    let mut reader = decoder.read_info().map_err(|e| e.to_string())?;
    let mut buf = vec![
        0;
        reader
            .output_buffer_size()
            .ok_or("output buffer size overflow")?
    ];
    let info = reader.next_frame(&mut buf).map_err(|e| e.to_string())?;
    buf.truncate(info.buffer_size());
    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => buf
            .as_chunks::<3>()
            .0
            .iter()
            .flat_map(|&[r, g, b]| [r, g, b, 255])
            .collect(),
        png::ColorType::GrayscaleAlpha => buf
            .as_chunks::<2>()
            .0
            .iter()
            .flat_map(|&[l, a]| [l, l, l, a])
            .collect(),
        png::ColorType::Grayscale => buf.iter().flat_map(|&l| [l, l, l, 255]).collect(),
        other => return Err(format!("unsupported color type {other:?}")),
    };
    Ok((info.width, info.height, rgba))
}

/// Register every `assets/*.png` under `dir` as an image named by its
/// filename stem.
fn register_assets(engine: &mut Engine, dir: &std::path::Path) -> Result<(), String> {
    let assets = dir.join("assets");
    if !assets.is_dir() {
        return Ok(());
    }
    let mut entries: Vec<_> = std::fs::read_dir(&assets)
        .map_err(|e| e.to_string())?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            if path.file_name().is_some_and(|n| n == "fonts") {
                register_fonts(engine, &path)?;
            } else {
                log::warn!("skipping asset directory {path:?}");
            }
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if path.extension().and_then(|e| e.to_str()) != Some("png") {
            log::warn!("skipping asset {path:?}: only .png is supported");
            continue;
        }
        let (width, height, rgba) =
            load_png(&path).map_err(|e| format!("cannot load asset {path:?}: {e}"))?;
        engine
            .set_image(stem, width, height, rgba)
            .map_err(|e| format!("cannot register asset {path:?}: {e}"))?;
        log::info!("registered asset {stem:?} ({width}x{height})");
    }
    Ok(())
}

/// Register every `*.fnt` in `dir` as a bitmap font named by its filename
/// stem; page images are PNGs next to it, as the description names them.
fn register_fonts(engine: &mut Engine, dir: &std::path::Path) -> Result<(), String> {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .map_err(|e| e.to_string())?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "fnt"))
        .collect();
    entries.sort();
    for path in entries {
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let fnt = std::fs::read_to_string(&path)
            .map_err(|e| format!("cannot read font {path:?}: {e}"))?;
        let font =
            BitmapFont::parse(&fnt).map_err(|e| format!("cannot parse font {path:?}: {e}"))?;
        let pages = font
            .pages()
            .iter()
            .map(|page| {
                let page_path = dir.join(page);
                load_png(&page_path)
                    .map_err(|e| format!("cannot load font page {page_path:?}: {e}"))
            })
            .collect::<Result<Vec<_>, _>>()?;
        engine
            .set_font(stem, font, pages)
            .map_err(|e| format!("cannot register font {path:?}: {e}"))?;
        log::info!("registered font {stem:?}");
    }
    Ok(())
}

fn load_driver(path: &str) -> Result<DriverState, String> {
    let json =
        std::fs::read_to_string(path).map_err(|e| format!("cannot read driver {path:?}: {e}"))?;
    let driver: Driver =
        serde_json::from_str(&json).map_err(|e| format!("cannot load driver {path:?}: {e}"))?;
    log::info!(
        "driving with {path:?}: {} steps{}",
        driver.steps.len(),
        if driver.looping { ", looping" } else { "" }
    );
    Ok(DriverState::new(driver))
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let path = std::env::args().nth(1).unwrap_or_else(|| {
        concat!(env!("CARGO_MANIFEST_DIR"), "/examples/shows/minigolf.json").to_owned()
    });

    // A directory is a show folder: show.json inside, assets/ registered,
    // test-driver.json picked up unless a driver is given explicitly.
    let mut engine = Engine::new();
    let mut folder_driver: Option<String> = None;
    let show_path = if std::path::Path::new(&path).is_dir() {
        let dir = std::path::PathBuf::from(&path);
        log::info!("starting player with show folder {path:?}");
        register_assets(&mut engine, &dir)?;
        let test_driver = dir.join("test-driver.json");
        if test_driver.is_file() {
            folder_driver = Some(test_driver.to_string_lossy().into_owned());
        }
        let manifest = dir.join("show.json");
        if !manifest.is_file() {
            return Err(format!("show folder {path:?} has no show.json").into());
        }
        manifest.to_string_lossy().into_owned()
    } else {
        log::info!("starting player with show {path:?}");
        path.clone()
    };
    let json = std::fs::read_to_string(&show_path)
        .map_err(|e| format!("cannot read show {show_path:?}: {e}"))?;
    engine
        .load_show(&json)
        .map_err(|e| format!("cannot load show {show_path:?}: {e}"))?;

    let driver = match std::env::args().nth(2).or(folder_driver) {
        Some(driver_path) => Some(load_driver(&driver_path)?),
        None => None,
    };

    let mut actions = BTreeSet::new();
    let show = engine.show().expect("show loaded");
    collect_show_actions(show, &mut actions);
    for layers in show.layer_trees() {
        warn_missing_images(&engine, layers);
    }
    let actions: Vec<String> = actions.into_iter().collect();
    print_menu(&engine, &actions);

    let (tx, rx) = std::sync::mpsc::channel();
    spawn_console_reader(tx);

    let mut app = App {
        engine,
        actions,
        driver,
        console: rx,
        context: RenderContext::new(),
        renderers: Vec::new(),
        state: None,
        occluded: false,
        last_frame: Instant::now(),
        fps: common::Fps::new(),
        images: ImageCache::new(),
        native: None,
    };
    let event_loop = EventLoop::new()?;
    event_loop.run_app(&mut app)?;
    log::info!("event loop finished, exiting");
    Ok(())
}
