[workspace]
resolver = "2"
members = [
    "crates/cuelight",
    "crates/cuelight-audio",
    "crates/cuelight-loader",
    "crates/cuelight-player",
    "crates/cuelight-web",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/francisdb/cuelight"

[profile.dev]
# vello/wgpu are unusably slow fully unoptimized
opt-level = 1